version: '3.1'

services:
  # app:
  #   build: .
  #   depends_on:
  #     - db
  #     - redis
  #   ports:
  #     - 3333:3000
  #   restart: always
  #   environment:
  #     SESSION_SECRET: asdffgmklmsdf
  #     SESSION_SECURE: 'false'
  #     SESSION_NAME: notyourbusinessfriend
  #     CERTIFICATE_UPLOAD_DIR: public/uploads/certificates
  #     HOST: http://localhost:3333
  #     REDIS_HOST: redis
  #     DB_HOST: db
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test
  redis:
    image: redis:6.2
    restart: always
    ports:
      - '6379:6379'
  rcli:
    image: redis:6.2
    links:
      - redis
    command: redis-cli -h redis
