version: '3.1'

services:
  # app:
  #   build: .
  #   depends_on:
  #     - db
  #     - redis
  #   ports:
  #     - 3333:3000
  #   restart: always
  #   environment:
  #     SESSION_SECRET: asdffgmklmsdf
  #     SESSION_SECURE: 'false'
  #     SESSION_NAME: notyourbusinessfriend
  #     CERTIFICATE_UPLOAD_DIR: public/uploads/certificates
  #     HOST: http://localhost:3333
  #     REDIS_HOST: redis
  #     DB_HOST: db
  db:
    image: postgres:14.2-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: test
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
  rcli:
    image: redis:6.2-alpine
    links:
      - redis
    command: redis-cli -h redis
