version: '3.1'

services:
  # app:
  #   build: .
  #   depends_on:
  #     - db
  #     - redis
  #   ports:
  #     - 3333:3000
  #   restart: always
  #   environment:
  #     SESSION_SECRET: asdffgmklmsdf
  #     SESSION_SECURE: 'false'
  #     SESSION_NAME: notyourbusinessfriend
  #     HOST: http://localhost:3333
  #     REDIS_HOST: redis
  #     DB_HOST: db
  db:
    image: postgres:14.2-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: test
  supertokensdb:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: supertokens
  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql
    restart: always
    ports:
      - 3567:3567
    environment:
      POSTGRESQL_CONNECTION_URI: postgresql://postgres:example@supertokensdb:5432/supertokens
      PASSWORD_HASHING_ALG: ARGON2
    depends_on:
      - supertokensdb
